name: expenses-dev-postgres

services:
  redis:
    image: redis:alpine
    container_name: expenses_redis_dev
    restart: unless-stopped
    # Comando per attivare la persistenza AOF
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Volume per salvare i file di persistenza
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  postgres:
    image: pgvector/pgvector:pg15
    container_name: expenses_db_dev
    environment:
      POSTGRES_DB: expensesdb
      POSTGRES_USER: expenses
      POSTGRES_PASSWORD: expenses
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expenses -d expensesdb"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - expense_categorizer_dev_data:/var/lib/postgresql/data
  celery-worker:
    build:
      context: .
    container_name: expense_categorizer_celery_worker
    command: celery -A server worker -l info
    volumes:
      - ./model_cache:/app/model_cache
    environment:
      FASTEMBED_CACHE_PATH: /app/model_cache
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: expensesdb
      DB_USER: expenses
      DB_PASSWORD: expenses
      GEMINI_API_KEY: AIzaSyCdcmmXxwzOKIQdrOogoeBPGlz2QNGDpJE
      GEMINI_MAX_RETRIES: 2
      GEMINI_BASE_DELAY: 1
      DJANGO_SETTINGS_MODULE: server.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
volumes:
  expense_categorizer_dev_data:
  redis_data: